// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SqlDataService.proto

package grpc.search.oauth.server.s.grpc.mdoel;

public interface ServerReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.ServerReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messagecode = 1;</code>
   */
  int getMessagecode();

  /**
   * <code>string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
