// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SqlDataService.proto

package grpc.search.oauth.server.s.grpc.mdoel;

public interface SqlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.SqlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string token = 2;</code>
   */
  String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string sql = 3;</code>
   */
  String getSql();
  /**
   * <code>string sql = 3;</code>
   */
  com.google.protobuf.ByteString
      getSqlBytes();

  /**
   * <code>string type = 4;</code>
   */
  String getType();
  /**
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string roleId = 5;</code>
   */
  String getRoleId();
  /**
   * <code>string roleId = 5;</code>
   */
  com.google.protobuf.ByteString
      getRoleIdBytes();

  /**
   * <code>string dataSourceName = 6;</code>
   */
  String getDataSourceName();
  /**
   * <code>string dataSourceName = 6;</code>
   */
  com.google.protobuf.ByteString
      getDataSourceNameBytes();
}
